import localFont from "next/font/local";
import "./globals.css";



export const metadata = {
  title: "SRI search",
  description: "A search engine with both text and voice input Generated by SRI Group",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
